In [1]:
import numpy as np

In [18]:
matris1 = [[1,2,3],
           [7,8,9]]
#2x3 boyutlu matris

In [19]:
matris1

[[1, 2, 3], [7, 8, 9]]

In [20]:
type(matris1)

list

In [21]:
matris2 = np.array([[1,2,3],[7,8,9]])

In [22]:
matris2

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
type(matris2)

numpy.ndarray

In [24]:
zerosArray = np.zeros((3,4))

In [26]:
zerosArray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
onesArray = np.ones((2,5))

In [28]:
onesArray

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
A = np.eye(4)

In [34]:
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
B = np.eye(6, k=2)
# k 1'lerin yerini değiştirir

In [44]:
B

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
C = np.eye(6, M=4)
# M kolon sayısını değiştirmeye yarar

In [51]:
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
yeniMatris = np.matrix([[1,2],[3,4]])

In [71]:
yeniMatris

matrix([[1, 2],
        [3, 4]])

In [72]:
type(yeniMatris)

numpy.matrix

In [97]:
randomArray = np.random.randn(10)
# ortalama değeri 0, standart sapması 1 olan 10 sayı (Gaussian(normal))

In [98]:
randomArray

array([-0.82439508, -0.99023293, -1.47165208, -0.79361391,  0.46228349,
       -2.22838289,  0.7813471 , -1.19133125, -1.92740961,  1.54233987])

In [99]:
randomArray2 = np.random.randn(10,4)

In [100]:
randomArray2

array([[-0.23803699, -1.39768319,  0.46885075, -0.05324663],
       [ 0.38983457, -1.18933994,  0.20817859, -0.64070099],
       [-0.20510746, -0.37244751,  1.66854618, -0.50685741],
       [-1.10673004,  1.3451252 ,  1.128621  ,  0.30884359],
       [ 0.88170771, -1.51351132,  1.11194061,  0.47253792],
       [ 0.39505496,  1.6353311 , -0.65614371,  1.36690046],
       [-0.68233744,  0.95209472,  0.28468466,  0.51158221],
       [-0.87450957,  0.44876311,  1.20036045, -0.11695705],
       [ 2.04857037, -0.07334563,  0.21622932,  0.34906627],
       [ 1.04342638,  1.38894645, -1.14319354, -0.87157626]])

In [102]:
np.random.rand(10)
#0-1 aralığında eşit dağılımlı 10 sayı (uniform)

array([0.63801212, 0.34338115, 0.14842109, 0.01491649, 0.87554511,
       0.693384  , 0.91615018, 0.08370163, 0.79957966, 0.89745369])